name: quasispecies-reconstruction
channels:
  - stephenshank
  - davebx
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _r-mutex=1.0.1=anacondar_1
  - abayesqr=1.0.0=h6bb024c_4
  - aioeasywebdav=2.4.0=py36_1000
  - aiohttp=3.5.4=py36h14c3975_0
  - appdirs=1.4.3=py_1
  - art=2016.06.05=gsl1.16_0
  - asn1crypto=0.24.0=py36_1003
  - async-timeout=3.0.1=py_1000
  - attrs=19.1.0=py_0
  - bcftools=1.9=ha228f0b_4
  - bcrypt=3.1.6=py36h516909a_1
  - binutils_impl_linux-64=2.31.1=h6176602_1
  - binutils_linux-64=2.31.1=h6176602_7
  - bioconductor-biobase=2.42.0=r351h14c3975_0
  - bioconductor-biocgenerics=0.28.0=r351_1
  - bioconductor-biocparallel=1.16.5=r351h1c2f66e_1
  - bioconductor-biostrings=2.50.2=r351h14c3975_1
  - bioconductor-delayedarray=0.8.0=r351h14c3975_1
  - bioconductor-genomeinfodb=1.18.1=r351_0
  - bioconductor-genomeinfodbdata=1.2.0=r351_0
  - bioconductor-genomicalignments=1.18.1=r351h14c3975_0
  - bioconductor-genomicranges=1.34.0=r351h14c3975_0
  - bioconductor-iranges=2.16.0=r351h14c3975_0
  - bioconductor-noiseq=2.26.1=r351_0
  - bioconductor-rsamtools=1.34.0=r351hf484d3e_0
  - bioconductor-rtracklayer=1.42.1=r351h9d9f1b6_1
  - bioconductor-s4vectors=0.20.1=r351h14c3975_0
  - bioconductor-summarizedexperiment=1.12.0=r351_1
  - bioconductor-xvector=0.22.0=r351h14c3975_0
  - bioconductor-zlibbioc=1.28.0=r351h14c3975_0
  - biopython=1.73=py36h14c3975_0
  - blas=2.11=openblas
  - boto3=1.9.199=py_0
  - botocore=1.12.199=py_0
  - bowtie2=2.3.4.3=py36he860b03_1
  - bwa=0.7.17=hed695b0_6
  - bwidget=1.9.11=0
  - bzip2=1.0.8=h516909a_0
  - ca-certificates=2019.6.16=hecc5488_0
  - cachetools=2.1.0=py_0
  - cairo=1.14.12=h80bd089_1005
  - certifi=2019.6.16=py36_1
  - cffi=1.12.3=py36h8022711_0
  - chardet=3.0.4=py36_1003
  - click=7.0=py_0
  - configargparse=0.13.0=py_1
  - convex-qsr=0.2.0=py36_1
  - cryptography=2.7=py36h72c5cf5_0
  - curl=7.65.3=hf8cf82a_0
  - cython=0.29.13=py36he1b5a44_0
  - datrie=0.7.1=py36h14c3975_0
  - decorator=4.4.0=py_0
  - docutils=0.14=py36_1001
  - dropbox=9.4.0=py_0
  - expat=2.2.5=he1b5a44_1003
  - fastp=0.19.7=hdbcaa40_0
  - fastqc=0.11.8=1
  - filechunkio=1.8=py_2
  - flask=1.1.1=py_0
  - font-ttf-dejavu-sans-mono=2.37=h6964260_0
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.10.0=he983fc9_0
  - ftputil=3.4=py_0
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_7
  - gettext=0.19.8.1=hc5be6a0_1002
  - gfortran_impl_linux-64=7.3.0=hdf63c60_1
  - gfortran_linux-64=7.3.0=h553295d_7
  - gitdb2=2.0.5=py_0
  - gitpython=2.1.13=py_0
  - glib=2.56.2=had28632_1001
  - google-api-core=1.14.2=py36_0
  - google-auth=1.6.3=py_0
  - google-cloud-core=1.0.3=py_0
  - google-cloud-storage=1.17.0=py_0
  - google-resumable-media=0.3.2=py_0
  - googleapis-common-protos=1.6.0=py36_0
  - graphite2=1.3.13=hf484d3e_1000
  - graphviz=2.38.0=hcf1ce16_1009
  - gsl=1.16=0
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_7
  - harfbuzz=1.9.0=he243708_1001
  - htslib=1.9=ha228f0b_7
  - icu=58.2=hf484d3e_1000
  - idna=2.8=py36_1000
  - idna_ssl=1.1.0=py36_1000
  - itsdangerous=1.1.0=py_0
  - java-jdk=7.0.91=1
  - jinja2=2.10.1=py_0
  - jmespath=0.9.4=py_0
  - jpeg=9c=h14c3975_1001
  - jsonschema=3.0.1=py36_0
  - krb5=1.16.3=h05b26f9_1001
  - libblas=3.8.0=11_openblas
  - libcblas=3.8.0=11_openblas
  - libcurl=7.65.3=hda55be3_0
  - libdeflate=1.0=h14c3975_1
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1006
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1005
  - libidn2=2.1.1=h14c3975_0
  - liblapack=3.8.0=11_openblas
  - liblapacke=3.8.0=11_openblas
  - libopenblas=0.3.6=h6e990d7_6
  - libpng=1.6.37=hed695b0_0
  - libprotobuf=3.9.0=h8b12597_0
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h57b8799_1003
  - libtool=2.4.6=h14c3975_1002
  - libunistring=0.9.10=h14c3975_0
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=h13577e0_2
  - lz4-c=1.8.3=he1b5a44_1001
  - mafft=7.407=hf484d3e_2
  - make=4.2.1=h14c3975_2004
  - markupsafe=1.1.1=py36h14c3975_0
  - multidict=4.5.2=py36h14c3975_1000
  - ncurses=6.1=hf484d3e_1002
  - networkx=2.3=py_0
  - numpy=1.17.0=py36h95a1406_0
  - openjdk=11.0.1=h516909a_1016
  - openssl=1.1.1c=h516909a_0
  - pandas=0.25.0=py36hb3f55d8_0
  - pandoc=2.7.3=0
  - pango=1.40.14=hf0c64fd_1003
  - paramiko=2.6.0=py36_0
  - pcre=8.41=hf484d3e_1003
  - perl=5.26.2=h516909a_1006
  - pip=19.2.1=py36_0
  - pixman=0.34.0=h14c3975_1003
  - prettytable=0.7.2=py_3
  - protobuf=3.9.0=py36he1b5a44_0
  - psutil=5.6.3=py36h516909a_0
  - pthread-stubs=0.4=h14c3975_1001
  - pyasn1=0.4.5=py_0
  - pyasn1-modules=0.2.5=py_0
  - pycparser=2.19=py36_1
  - pygments=2.4.2=py_0
  - pygraphviz=1.5=py36h516909a_1001
  - pynacl=1.3.0=py36h14c3975_1000
  - pyopenssl=19.0.0=py36_0
  - pyrsistent=0.15.4=py36h516909a_0
  - pysam=0.15.3=py36h5ad169c_0
  - pysftp=0.2.9=py_1
  - pysocks=1.7.0=py36_0
  - python=3.6.7=h381d211_1004
  - python-dateutil=2.8.0=py_0
  - python-irodsclient=0.7.0=py_0
  - pytz=2019.2=py_0
  - pyyaml=5.1.2=py36h516909a_0
  - qualimap=2.2.2c=1
  - r-askpass=1.1=r35hcdcec82_1
  - r-assertthat=0.2.1=r35h6115d3f_1
  - r-backports=1.1.4=r35hcdcec82_1
  - r-base=3.5.1=he45234b_1005
  - r-base64enc=0.1_3=r35hcdcec82_1003
  - r-bh=1.69.0_1=r35h6115d3f_1
  - r-bitops=1.0_6=r35hcdcec82_1003
  - r-broom=0.5.2=r35h6115d3f_1
  - r-callr=3.3.0=r35h6115d3f_1
  - r-cellranger=1.1.0=r35h6115d3f_1002
  - r-cli=1.1.0=r35h6115d3f_1
  - r-clipr=0.7.0=r35h6115d3f_0
  - r-colorspace=1.4_1=r35hcdcec82_1
  - r-crayon=1.3.4=r35h6115d3f_1002
  - r-curl=4.0=r35hcdcec82_0
  - r-dbi=1.0.0=r35h6115d3f_1002
  - r-dbplyr=1.4.2=r35h6115d3f_1
  - r-digest=0.6.20=r35h0357c0b_1
  - r-dplyr=0.8.3=r35h0357c0b_1
  - r-ellipsis=0.2.0.1=r35hcdcec82_1
  - r-evaluate=0.14=r35h6115d3f_1
  - r-fansi=0.4.0=r35hcdcec82_1001
  - r-forcats=0.4.0=r35h6115d3f_1
  - r-formatr=1.7=r35h6115d3f_1
  - r-fs=1.3.1=r35h0357c0b_1
  - r-futile.logger=1.4.3=r35h6115d3f_1002
  - r-futile.options=1.0.1=r35h6115d3f_1001
  - r-generics=0.0.2=r35h6115d3f_1002
  - r-getopt=1.20.3=r35_1
  - r-ggplot2=3.2.0=r35h6115d3f_1
  - r-glue=1.3.1=r35hcdcec82_1
  - r-gtable=0.3.0=r35h6115d3f_2
  - r-haven=2.1.1=r35h0357c0b_1
  - r-highr=0.8=r35h6115d3f_1
  - r-hms=0.5.0=r35h6115d3f_1
  - r-htmltools=0.3.6=r35he1b5a44_1003
  - r-httr=1.4.0=r35h6115d3f_1001
  - r-igraph=1.2.4.1=r35h6786f55_1
  - r-jsonlite=1.6=r35hcdcec82_1001
  - r-knitr=1.23=r35h6115d3f_1
  - r-labeling=0.3=r35h6115d3f_1002
  - r-lambda.r=1.2.3=r35h6115d3f_1001
  - r-lattice=0.20_38=r35hcdcec82_1002
  - r-lazyeval=0.2.2=r35hcdcec82_1
  - r-lubridate=1.7.4=r35h0357c0b_1002
  - r-magrittr=1.5=r35h6115d3f_1002
  - r-markdown=1.0=r35hcdcec82_1
  - r-mass=7.3_51.4=r35hcdcec82_1
  - r-matrix=1.2_17=r35hcdcec82_1
  - r-matrixstats=0.54.0=r35hcdcec82_1001
  - r-mgcv=1.8_28=r35hcdcec82_1
  - r-mime=0.7=r35hcdcec82_1
  - r-modelr=0.1.4=r35h6115d3f_1
  - r-munsell=0.5.0=r35h6115d3f_1002
  - r-nlme=3.1_140=r35h9bbef5b_1
  - r-openssl=1.4=r35h9c8475f_1
  - r-optparse=1.6.2=r35h6115d3f_1
  - r-pillar=1.4.2=r35h6115d3f_2
  - r-pkgconfig=2.0.2=r35h6115d3f_1002
  - r-plogr=0.2.0=r35h6115d3f_1002
  - r-plyr=1.8.4=r35h0357c0b_1003
  - r-prettyunits=1.0.2=r35h6115d3f_1002
  - r-processx=3.4.0=r35hcdcec82_1
  - r-progress=1.2.2=r35h6115d3f_1
  - r-ps=1.3.0=r35hcdcec82_1001
  - r-purrr=0.3.2=r35hcdcec82_1
  - r-r6=2.4.0=r35h6115d3f_2
  - r-rcolorbrewer=1.1_2=r35h6115d3f_1002
  - r-rcpp=1.0.2=r35h0357c0b_0
  - r-rcurl=1.95_4.12=r35hcdcec82_1
  - r-readr=1.3.1=r35h0357c0b_1001
  - r-readxl=1.3.1=r35h0357c0b_1
  - r-regresshaplo=1.0.0=r351_9
  - r-rematch=1.0.1=r35h6115d3f_1002
  - r-reprex=0.3.0=r35h6115d3f_1
  - r-reshape2=1.4.3=r35h0357c0b_1004
  - r-rlang=0.4.0=r35hcdcec82_1
  - r-rmarkdown=1.14=r35h6115d3f_1
  - r-rmutil=1.1.1=r351ha65eedd_0
  - r-rstudioapi=0.10=r35h6115d3f_1
  - r-rvest=0.3.4=r35h6115d3f_1
  - r-scales=1.0.0=r35h0357c0b_1002
  - r-selectr=0.4_1=r35h6115d3f_1001
  - r-snow=0.4_3=r35h6115d3f_1001
  - r-stringi=1.4.3=r35h0357c0b_2
  - r-stringr=1.4.0=r35h6115d3f_1
  - r-sys=3.2=r35hcdcec82_1
  - r-tibble=2.1.3=r35hcdcec82_1
  - r-tidyr=0.8.3=r35h0357c0b_1
  - r-tidyselect=0.2.5=r35h0357c0b_1001
  - r-tidyverse=1.2.1=r35h6115d3f_1002
  - r-tinytex=0.14=r35h6115d3f_1
  - r-utf8=1.1.4=r35hcdcec82_1001
  - r-vctrs=0.2.0=r35hcdcec82_1
  - r-viridislite=0.3.0=r35h6115d3f_1002
  - r-whisker=0.3_2=r35h6115d3f_1002
  - r-withr=2.1.2=r35h6115d3f_1001
  - r-xfun=0.8=r35h6115d3f_1
  - r-xml=3.98_1.20=r35hcdcec82_1
  - r-xml2=1.2.1=r35h0357c0b_0
  - r-yaml=2.2.0=r35hcdcec82_1002
  - r-zeallot=0.1.0=r35h6115d3f_1001
  - ratelimiter=1.2.0=py36_1000
  - readline=7.0=hf8c457e_1001
  - requests=2.22.0=py36_1
  - rsa=3.4.2=py_1
  - s3transfer=0.2.1=py36_0
  - samtools=1.9=h8571acd_11
  - scipy=1.3.0=py36h921218d_1
  - setuptools=41.0.1=py36_0
  - six=1.12.0=py36_1000
  - smmap2=2.0.5=py_0
  - snakemake=5.5.4=1
  - snakemake-minimal=5.5.4=py_1
  - sqlite=3.28.0=h8b20d00_0
  - tbb=2019.7=hc9558a2_0
  - tk=8.6.9=hed695b0_1002
  - tktable=2.10=h555a92e_1
  - trimmomatic=0.39=1
  - typing_extensions=3.7.4=py36_0
  - urllib3=1.25.3=py36_0
  - werkzeug=0.15.5=py_0
  - wget=1.20.1=h90d6eec_0
  - wheel=0.33.4=py36_0
  - wrapt=1.11.2=py36h516909a_0
  - xmlrunner=1.7.7=py_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.8=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxpm=3.5.12=h14c3975_1002
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxt=1.1.5=h516909a_1003
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - yaml=0.1.7=h14c3975_1001
  - yarl=1.3.0=py36h14c3975_1000
  - zlib=1.2.11=h516909a_1005
  - zstd=1.4.0=h3b9ef0a_0
  - pip:
    - bioext==0.19.5
    - joblib==0.13.2
prefix: /home/sshank/Software/anaconda3/envs/quasispecies-reconstruction

